### ISSUE TITLE
What is the dataset that is used for the results shown?  (240 or augmented version?)

### ISSUE THREAD

**Issue by ManoharSai2000** [hlwang1124/AAFramework#2]

**Comment by hlwang1124** [comment]
Hi, @ManoharSai2000 . The original version with 240 images.

**Comment by ManoharSai2000** [comment]
Is it really sufficient, I mean is it pretrained on any other datasets?

**Comment by hlwang1124** [comment]
Yes. We used the pretrained weights provided by `torchvision`.

**Comment by ManoharSai2000** [comment]
Thanks for your reply.
BUT, your network is new right?
How did you get the pre trained weights from torchvision?
Sorry for asking so many questions!

**Comment by hlwang1124** [comment]
We only used the pre-trained weights for the backbone. Specifically, we trained AA-UNet from scratch. But for AA-RTFNet, since the backbone of RTFNet is ResNet, we used the corresponding pre-trained weights from `torchvision`.

**Comment by ManoharSai2000** [comment]
Thank you.
For the AAUnet, did you not get any overfitting problems beacause of the
limited dataset?

**Comment by hlwang1124** [comment]
Actually, not very obvious.
